### ISSUE TITLE
Cannot switch certificates

### ISSUE THREAD

**Issue by carlgust** [arnef/coronaapp#29]
I have two certificates on my Nexus5. One for me and one for my girl friend. If CoronaApp starts, I can see two dots below the certificate. Touching the dots do not switch certificates. It seems the dots are not touch sensible.

**Comment by arnef** [comment]
the dots are not touchable, they are only indicators. you must swipe left/right to switch the certificates

**Comment by carlgust** [comment]
Thank you. That's it. And thank you for the app.
