### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by Thieb67k** [arnef/coronaapp#4]
Hello,

I did try the corona App on my LG nexus4 but the screen remains white.
When I swipe to the top I can flash a QR core but then, back the the white screen, nothing happens...

I hope that helps.
Best,

**Comment by kaelte** [comment]
Same issue on my Fairphone 2.

**Comment by arnef** [comment]
just to be sure...you scanned a vaccination certificate? test and recovery certificates are not supported at the moment

**Comment by Thieb67k** [comment]
I see. In my case it is a test certificate. Hence, I will be patient :)
Nevertheless, when I open the App, the screen is white. Is that the normal behavior?
Thanks
![screenshot20210723_074826103](https://user-images.githubusercontent.com/44848877/126742107-50a53723-3e33-4a66-91a9-19bd7902350c.png)

**Comment by arnef** [comment]
should be closed with #7
