### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by xdub** [arnef/coronaapp#6]
Would it be possible to modify the application for translation into other languages?

I use the application in the Czech Republic on my BQ Aquaris E4.5. It works perfectly.

**Comment by Vistaus** [comment]
I support this. If implemented, I will provide the Dutch translation 🙂

**Comment by gbdomubpkm** [comment]
The app in French would be great. And thanks in advance for our specialist @Anne017 when the work possible.

**Comment by arnef** [comment]
:rocket: go for it

**Comment by sc-fx** [comment]
# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: \n"
"Report-Msgid-Bugs-To: EMAIL\n"
"POT-Creation-Date: 2021-07-28 23:39+0200\n"
"PO-Revision-Date: 2021-07-30 20:50+0200\n"
"Language-Team: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: Poedit 2.4.2\n"
"Last-Translator: \n"
"Plural-Forms: nplurals=2; plural=(n==1 ? 0 : 1);\n"
"Language: fr\n"

#: app/viewmodel/vaccination.go:23
msgid "Vaccine Type"
msgstr "Type de vaccin"

#: app/viewmodel/cert.go:59
msgid "Vaccination certificate"
msgstr "Certificat de vaccination"

#: app/viewmodel/cert.go:81
msgid "Full vaccination protection"
msgstr "Protection vaccination complète"

#: app/viewmodel/vaccination.go:19
msgid "Vaccine"
msgstr "Vaccin"

#: app/viewmodel/recovery.go:18
msgid "Date of first positive test result (YYYY-MM-DD)"
msgstr "Date du résultat du premier test positif (YYYY-MM-DD)"

#: app/viewmodel/test.go:18
msgid "Type of test"
msgstr "Type de test"

#: app/viewmodel/test.go:30
msgid "Date and time of the sample collection (YYYY-MM-DD, HH:MM)"
msgstr "Date et heure du prélèvement (YYYY-MM-DD, HH:MM)"

#: app/viewmodel/test.go:26
msgid "Test manufacturer"
msgstr "Fabricant du test"

#: app/viewmodel/test.go:38
msgid "Testing centre or facility"
msgstr "Centre de test ou assimilé"

#: app/viewmodel/cert.go:62
msgid "Recovery certificate"
msgstr "Certificat de guérison"

#: app/viewmodel/cert.go:85
#, c-format
msgid "Full protection as of %s"
msgstr "Protection pleine à partir de %s"

#: main.go:65
msgid "Delete certificate?"
msgstr "Supprimer le certificat ?"

#: main.go:66
msgid "Cancel"
msgstr "Annulation"

#: app/viewmodel/vaccination.go:47 app/viewmodel/recovery.go:38
#: app/viewmodel/test.go:50
msgid "Unique certificate identifier"
msgstr "Identifiant unique de certificat"

#: app/viewmodel/recovery.go:14
msgid "Disease or agent the citizen has recovered from"
msgstr "Maladie ou agent dont le citoyen est guéri"

#: app/viewmodel/cert.go:88
msgid "Incomplete vaccination protection"
msgstr "Protection de vaccination incomplète"

#: app/viewmodel/vaccination.go:15 app/viewmodel/test.go:14
msgid "Disease or agent targeted"
msgstr "Maladie ou agent ciblé"

#: app/viewmodel/vaccination.go:31
msgid "Number in a series of vaccinations/doses"
msgstr "Numéro dans une série de vaccinations/doses"

#: app/viewmodel/vaccination.go:39
msgid "Member State of vaccination"
msgstr "Etat Membre de vaccination"

#: app/viewmodel/test.go:22
msgid "Test name"
msgstr "Nom du test"

#: app/viewmodel/vaccination.go:27
msgid "Manufacturer"
msgstr "Fabricant"

#: app/viewmodel/test.go:34
msgid "Test result"
msgstr "Résultat du test"

#: app/viewmodel/cert.go:32
msgid "Name, first name"
msgstr "Nom, prénom"

#: app/viewmodel/cert.go:36
msgid "Date of birth (YYYY-MM-DD)"
msgstr "Date de naissance (YYYY-MM-DD)"

#: app/viewmodel/cert.go:68
msgid "PCR test"
msgstr "Test PCR"

#: app/viewmodel/cert.go:94
#, c-format
msgid "Valid until %s"
msgstr "Valide jusqu'à %s"

#: app/state.go:23
msgid "You currently do not have saved any digital EU-COVID certificates."
msgstr "Vous n'avez sauvegardé aucun certificat numérique COVID-UE."

#: app/viewmodel/vaccination.go:35
msgid "Date of vaccination (YYYY-MM-DD)"
msgstr "Date de vaccination (YYYY-MM-DD)"

#: app/viewmodel/vaccination.go:43 app/viewmodel/recovery.go:26
#: app/viewmodel/test.go:46
msgid "Certificate issuer"
msgstr "Fournisseur du certificat"

#: app/viewmodel/recovery.go:22 app/viewmodel/test.go:42
msgid "Member State of test"
msgstr "Etat Membre du test"

#: main.go:64
msgid "Delete"
msgstr "Supprimer"

#: app/viewmodel/recovery.go:30
msgid "Certificate valid from (YYYY-MM-DD)"
msgstr Certificat valide à partir de (RRRR-MM-DD)"

#: app/viewmodel/recovery.go:34
msgid ""
"Certificate valid until (no more than 180 days after the date of first "
"positive test result)(YYYY-MM-DD)"
msgstr ""
"Certificat valide jusqu'à (pas plus de 180 jours au delà de la date du premier"
"résultat de test positif)(YYYY-MM-DD)"

#: app/viewmodel/cert.go:70
msgid "Rapid antigen test"
msgstr "Test antigénique rapide"

**Comment by Vistaus** [comment]
@sc-fx It's better to open a pull request 🙂

**Comment by sc-fx** [comment]
(this is a french translation file fr.po)

**Comment by sc-fx** [comment]
OK Vistaus, I try the pull request

**Comment by sc-fx** [comment]
@Vistaus : I am unable to create a new branch
Permission to arnef/coronaapp.git denied
It is the first step to create a pull request isn't it ?

**Comment by timsueberkrueb** [comment]
Hey @sc-fx, the easiest way with the GUI would be:

* Press the `fork` button in the top right corner
* Select your username
* Go to the newly created repository (e.g. https://github.com/sc-fx/coronaapp)
* Click on the `po` folder
* Select `Add file > Upload new file` or `Create new file` and add your translation
* Click on the green "Open pull-request` button.
* Leave the settings as is and click "Create pull-request"

**Comment by sc-fx** [comment]
Done ! Thanks @timsueberkrueb.
I must have done something wrong with the command line, but I was able to create the pull request following your instructions.

**Comment by gbdomubpkm** [comment]
Thank you @sc-fx !

**Comment by arnef** [comment]
i just released version 1.2.1 including your translations....

**Comment by sc-fx** [comment]
Thanks @arnef . I just made a very slight correction to a translation 
-which can be integrated later into another release-

**Comment by ghost** [comment]
@gbdomubpkm I took a summer break, but I see a French translation was proposed. I only have minor improvements to suggest, summarized in #24 

@arnef I think this issue can be closed now

**Comment by sc-fx** [comment]
Agree with everything. Thanks @arnef !

**Comment by gbdomubpkm** [comment]
@arnef  About the formatting of dates:
The French presentation of a date has the form JJ-MM-AAAA  (DD-MM-YYYY) and not AAAA-MM-JJ (YYYY-MM-DD). Shouldn't the French formatting be applied?

**Comment by arnef** [comment]
> @arnef About the formatting of dates:
> The French presentation of a date has the form DD-MM-YYYY (DD-MM-YYYY) and not YYYY-MM-DD (YYYY-MM-DD). Shouldn't the French formatting be applied?

I think the values should be shown as they stored in the certificate and this is the international formatting...

**Comment by gbdomubpkm** [comment]
Ok, i have seen the paper certificate and you are right. 😉
